import csv
import math
import paho.mqtt.client as mqtt
import os
import sys

# Ensure stdout supports UTF-8 on Windows
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except AttributeError:
        pass

# 1. MQTT Broker Connection Configuration
MQTT_BROKER = "broker.hivemq.com"  # Public cloud broker
MQTT_PORT = 1883
MQTT_TOPIC_COMMANDS = "rover/motors/commands"

client = mqtt.Client()
client.connect(MQTT_BROKER, MQTT_PORT, 60)
client.loop_start()

# 2. Waypoint Ingestion Matrix
waypoints = []
script_dir = os.path.dirname(os.path.abspath(__file__))
csv_path = "outputs/csv/path_coordinates.csv"
if not os.path.exists(csv_path):
    csv_path = os.path.join(script_dir, "outputs", "csv", "path_coordinates.csv")

try:
    # Read the exact CSV format generated by TerrainPlan.py
    with open(csv_path, mode='r', encoding='utf-8') as file:
        reader = csv.DictReader(file)
        for row in reader:
            waypoints.append((float(row['real_x']), float(row['real_y'])))
    print(f"✓ Loaded {len(waypoints)} tracking waypoints successfully.")
except FileNotFoundError:
    print("❌ Error: path_coordinates.csv not found! Run TerrainPlan.py first.")

active_wp_idx = 0
current_heading = 0.0
last_x, last_y = 0.0, 0.0

def process_new_position(filtered_x, filtered_y):
    """
    Call this function inside your raw uwb_server loop 
    every time a fresh Kalman filter coordinate is solved!
    """
    global active_wp_idx, current_heading, last_x, last_y
    
    if active_wp_idx >= len(waypoints):
        # Path complete: Publish absolute halt command
        client.publish(MQTT_TOPIC_COMMANDS, "0,0")
        return

    target_x, target_y = waypoints[active_wp_idx]
    
    # Calculate distance error to active waypoint
    dx = target_x - filtered_x
    dy = target_y - filtered_y
    distance = math.sqrt(dx**2 + dy**2)
    
    # Waypoint Acceptance Threshold (30 cm)
    if distance < 0.30:
        print(f"✓ Waypoint {active_wp_idx} cleared. Target shifted.")
        active_wp_idx += 1
        return

    # Estimate current orientation orientation based on displacement vectors
    move_dx = filtered_x - last_x
    move_dy = filtered_y - last_y
    if math.sqrt(move_dx**2 + move_dy**2) > 0.02:
        current_heading = math.atan2(move_dy, move_dx)

    # Compute Heading Corrections
    target_angle = math.atan2(dy, dx)
    heading_error = target_angle - current_heading
    
    # Normalize steering angles between -pi and +pi
    heading_error = (heading_error + math.pi) % (2 * math.pi) - math.pi
    
    # Differential Drive Steering Proportional Transform Logic
    base_speed = 180
    kp = 70.0  # Proportional steering sensitivity scalar
    steering_bias = int(heading_error * kp)
    
    left_speed = base_speed - steering_bias
    right_speed = base_speed + steering_bias
    
    # Clamp velocities to hardware 8-bit registers (0-255)
    left_speed = max(0, min(255, left_speed))
    right_speed = max(0, min(255, right_speed))
    
    # Package into lightweight ASCII token CSV payloads
    payload = f"{left_speed},{right_speed}"
    client.publish(MQTT_TOPIC_COMMANDS, payload)
    
    # Cache metrics for next loop displacement tracking
    last_x, last_y = filtered_x, filtered_y